### ISSUE TITLE
Broken link in Core

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/subdomain-link#2]
**Updated:** Broken links

- [ ] https://link.classicpress.net/core-privacy-policy/ in the about section > privacy of the CP Core.
- [ ] https://link.classicpress.net/the-cms-for-creators Ref https://github.com/ClassicPress/ClassicPress/pull/654

<img width="1089" alt="Screenshot 2021-01-23 at 19 24 22" src="https://user-images.githubusercontent.com/7713923/105624313-e139c480-5e31-11eb-8bd0-86f6fc3a6699.png">

**Comment by nylen** [comment]
Thanks. I can think of two ways to fix this:

- Create a privacy policy page for ClassicPress core
- Direct https://link.classicpress.net/core-privacy-policy/ to there

Or a temporary fix:

- Add a brief section to https://www.classicpress.net/privacy-policy/ that indicates that the core privacy policy is coming soon, and recommends studying the core code in the meantime
- Direct https://link.classicpress.net/core-privacy-policy/ to https://www.classicpress.net/privacy-policy/#core-privacy-policy (or whatever the subheading ID ends up being)

**Comment by nylen** [comment]
Thanks. I can think of two ways to fix this:

- Create a privacy policy page for ClassicPress core
- Direct https://link.classicpress.net/core-privacy-policy/ to there

Or a temporary fix:

- Add a brief section to https://www.classicpress.net/privacy-policy/ that indicates that the core privacy policy is coming soon, and recommends studying the core code in the meantime
- Direct https://link.classicpress.net/core-privacy-policy/ to https://www.classicpress.net/privacy-policy/#core-privacy-policy (or whatever the subheading ID ends up being)

@timbocode what do you think?

**Comment by timbocode** [comment]
I personally think the latter for now. I think a "coming soon" section on an existing page is less conspicuous than creating a new, empty page.

With that in mind, I've added a "Core Privacy Policy" section to the Privacy Policy, so the https://www.classicpress.net/privacy-policy/#core-privacy-policy link will now work. The https://link.classicpress.net/core-privacy-policy/ link just needs to be redirected to this section.

The Privacy Policy as a whole needs some work on it anyway.

**Comment by bahiirwa** [comment]
Adding this to fixes. https://github.com/ClassicPress/ClassicPress/pull/654#discussion_r626223721

**Comment by nylen** [comment]
3 total links need adding/fixing from https://github.com/ClassicPress/ClassicPress/pull/654:

- https://link.classicpress.net/releases/ can point to https://github.com/ClassicPress/ClassicPress-release/releases
- https://link.classicpress.net/petitions/ can point to https://forums.classicpress.net/c/governance/petitions/77
- https://link.classicpress.net/the-cms-for-creators/ - probably the best place to point this for now is at the marketing meeting transcript where we decided this tagline
